import type { PipelineStep, Candidate } from "@/types";
import type { FilterParams } from "@/types";

export const STEP_DEFINITIONS: Omit<PipelineStep, "status" | "inputCount" | "outputCount" | "passRate" | "mainExclusionReason">[] = [
  {
    key: "fragment",
    label: "片段提取 / Fragment",
    description: "Extract candidate peptide fragments from the protein sequence based on length constraints.",
  },
  {
    key: "charge",
    label: "电荷筛选 / Charge",
    description: "Filter candidates by net charge at pH 7.4 within the specified range.",
  },
  {
    key: "gravy",
    label: "疏水性筛选 / GRAVY",
    description: "Filter by grand average of hydropathicity (GRAVY) score.",
  },
  {
    key: "pi",
    label: "等电点筛选 / pI",
    description: "Filter by isoelectric point (pI) within the specified range.",
  },
  {
    key: "cysteine",
    label: "半胱氨酸筛选 / Cysteine",
    description: "Filter by cysteine count to control disulfide bond formation risk.",
  },
];

export const DEFAULT_PARAMS: FilterParams = {
  proteinName: "user_seq",
  proteinSequence: "",
  candidateCount: 120,
  lenMin: 5,
  lenMax: 15,
  chargeMin: -2,
  chargeMax: 2,
  gravyMin: -2,
  gravyMax: 2,
  piMin: 5,
  piMax: 9,
  cysMax: 2,
  disulfideWeight: 0.25,
  chargeWeight: 0.25,
  hydrophobicityWeight: 0.25,
  piWeight: 0.25,
};

export const RISK_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  low: { bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200" },
  medium: { bg: "bg-blue-50", text: "text-blue-700", border: "border-blue-200" },
  high: { bg: "bg-rose-50", text: "text-rose-700", border: "border-rose-200" },
  unknown: { bg: "bg-slate-50", text: "text-slate-500", border: "border-slate-200" },
};

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: "1-MKWVTFISL",
    rank: 1,
    sequence: "MKWVTFISL",
    length: 9,
    priorityScore: 0.92,
    disulfideScore: 0.95,
    chargeScore: 0.88,
    hydrophobicityScore: 0.85,
    pIScore: 0.91,
    netCharge: 1.2,
    gravy: -0.34,
    pI: 6.8,
    cysCount: 0,
    disulfideRisk: "low",
    rankingReason: "Excellent overall profile with low disulfide risk, balanced charge, and favorable hydrophobicity.",
    topAdvantages: ["Zero cysteine residues", "Optimal charge balance", "Favorable hydrophobicity"],
    passLength: true,
    passCharge: true,
    passGravy: true,
    passPI: true,
    passCys: true,
  },
  {
    id: "2-KFLRAHP",
    rank: 2,
    sequence: "KFLRAHP",
    length: 7,
    priorityScore: 0.87,
    disulfideScore: 0.82,
    chargeScore: 0.91,
    hydrophobicityScore: 0.78,
    pIScore: 0.95,
    netCharge: 2.1,
    gravy: -1.02,
    pI: 8.4,
    cysCount: 0,
    disulfideRisk: "low",
    rankingReason: "Strong charge profile with good pI score. Slightly less optimal hydrophobicity.",
    topAdvantages: ["High pI score", "Good charge properties", "Low disulfide risk"],
    passLength: true,
    passCharge: true,
    passGravy: true,
    passPI: true,
    passCys: true,
  },
  {
    id: "3-QSTSHS",
    rank: 3,
    sequence: "QSTSHS",
    length: 6,
    priorityScore: 0.81,
    disulfideScore: 0.76,
    chargeScore: 0.72,
    hydrophobicityScore: 0.88,
    pIScore: 0.85,
    netCharge: -0.5,
    gravy: 0.45,
    pI: 5.9,
    cysCount: 1,
    disulfideRisk: "medium",
    rankingReason: "Good hydrophobicity but elevated disulfide risk due to single cysteine.",
    topAdvantages: ["Good hydrophobicity score", "Balanced overall"],
    passLength: true,
    passCharge: true,
    passGravy: true,
    passPI: true,
    passCys: true,
  },
];
