export const TEXT = {
  pageTitle: 'TARGETING PEPTIDE',
  pageSubtitle: 'Design and evaluate targeting peptides, linkers and STAMP candidates.',
  linkerTitle: 'LINKER',
  stampTitle: 'STAMP',
  linkerTab: 'LINKER',
  stampTab: 'STAMP',
  linkerOptionsTitle: 'Linker Options',
  linkerParamsTitle: 'Linker Parameters',
  generateBtn: 'Generate Linker Candidates',
  resetBtn: 'Reset',
  linkerScoreTitle: '靶向肽 与 Linker 的评分',
  viewAllLinkers: 'View All Linker Candidates',
  stampInputTitle: 'Input Targeting Peptide + Linker',
  stampPlaceholder: 'Enter sequence or leave empty for de novo design',
  inputBtn: 'Input',
  clearBtn: 'Clear',
  advancedSettings: 'Advanced Settings',
  showMoreParams: 'Show more parameters',
  stampScoreTitle: '靶向肽、Linker 和 STAMP 的评分',
  viewDetailedReport: 'View Detailed Report',
  noticeText: '所有评分基于多参数筛选模型计算，结果仅供参考，请结合实验验证。',
  sidebar: {
    logoPrimary: '湘湖实验室',
    logoSecondary: 'XIANGHU LABORATORY',
    logoTertiary: '动物疫病疫苗团队',
    logoQuaternary: 'Animal Disease Control and Vaccine Team',
    navHome: 'Home',
    navPipeline: 'Pipeline',
    navTargeting: 'Targeting Peptide',
    navLinkerStamp: 'Linker & STAMP',
    navStructure: 'Structure',
    navResults: 'Results',
    navTeam: 'Team',
    navContact: 'Contact',
  },
  scoreLabels: {
    targetingPeptide: 'Targeting Peptide',
    linker: 'Linker',
    stamp: 'STAMP',
    overall: 'Overall Score',
  },
  criteria: {
    targetingPeptide: ['低免疫原性', '高稳定性', '良好可溶性'] as string[],
    linker: ['长度合适', '柔性匹配', '电荷平衡'] as string[],
    stamp: ['高稳定性', '结构完整性', '低毒性'] as string[],
  },
} as const;
