"""baseline_init

Revision ID: fce11772abec
Revises: 
Create Date: 2026-05-13 02:18:45.588630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce11772abec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('batch_computation_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('artifact_dir', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_computation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_computation_items_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_computation_items_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_computation_items_project_id'), ['project_id'], unique=False)

    op.create_table('batch_computations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('artifact_dir', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_computations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_computations_project_id'), ['project_id'], unique=False)

    op.create_table('computation_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('computation_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_computation_artifacts_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_computation_artifacts_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_computation_artifacts_item_id'), ['item_id'], unique=False)

    op.create_table('file_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_backend', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_assets_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_assets_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_assets_job_id'), ['job_id'], unique=False)

    op.create_table('integration_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('integration_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('auth_mode', sa.String(length=20), nullable=False),
    sa.Column('token_secret_ref', sa.String(length=255), nullable=True),
    sa.Column('field_mapping_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('test_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compute_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('batch_type', sa.String(length=64), nullable=False),
    sa.Column('candidate_ids', sa.JSON(), nullable=True),
    sa.Column('pipeline_stages', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compute_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compute_batches_project_id'), ['project_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('server_host', sa.String(length=256), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('artifacts_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)

    op.create_table('target_proteins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('sequence_hash', sa.String(length=64), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('organism', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('uniprot_id', sa.String(length=20), nullable=True),
    sa.Column('pdb_id', sa.String(length=10), nullable=True),
    sa.Column('chain_id', sa.String(length=10), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sequence_hash', name='uq_project_seqhash')
    )
    with op.batch_alter_table('target_proteins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_proteins_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_proteins_sequence_hash'), ['sequence_hash'], unique=False)

    op.create_table('epitope_scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('target_protein_id', sa.String(length=36), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['target_protein_id'], ['target_proteins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('epitope_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_epitope_scans_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_epitope_scans_target_protein_id'), ['target_protein_id'], unique=False)

    op.create_table('epitope_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.String(length=500), nullable=False),
    sa.Column('net_charge', sa.Float(), nullable=True),
    sa.Column('hydrophobicity', sa.Float(), nullable=True),
    sa.Column('pi', sa.Float(), nullable=True),
    sa.Column('cys_count', sa.Integer(), nullable=True),
    sa.Column('surface_exposure_score', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('ranking_score', sa.Float(), nullable=True),
    sa.Column('filter_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['epitope_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('epitope_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_epitope_candidates_scan_id'), ['scan_id'], unique=False)

    op.create_table('stamp_generation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('epitope_id', sa.String(length=36), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('generator_name', sa.String(length=100), nullable=False),
    sa.Column('generator_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['epitope_id'], ['epitope_candidates.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stamp_generation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stamp_generation_runs_epitope_id'), ['epitope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stamp_generation_runs_project_id'), ['project_id'], unique=False)

    op.create_table('stamp_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('epitope_id', sa.String(length=36), nullable=True),
    sa.Column('generation_run_id', sa.String(length=36), nullable=True),
    sa.Column('targeting_peptide_seq', sa.String(length=500), nullable=False),
    sa.Column('linker_seq', sa.String(length=100), nullable=False),
    sa.Column('full_sequence', sa.Text(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['epitope_id'], ['epitope_candidates.id'], ),
    sa.ForeignKeyConstraint(['generation_run_id'], ['stamp_generation_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stamp_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stamp_candidates_epitope_id'), ['epitope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stamp_candidates_generation_run_id'), ['generation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stamp_candidates_project_id'), ['project_id'], unique=False)

    op.create_table('experimental_validation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_type', sa.String(length=50), nullable=False),
    sa.Column('organism', sa.String(length=100), nullable=True),
    sa.Column('strain', sa.String(length=100), nullable=True),
    sa.Column('protocol_name', sa.String(length=255), nullable=True),
    sa.Column('protocol_version', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('experiment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['stamp_candidates.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experimental_validation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experimental_validation_runs_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experimental_validation_runs_project_id'), ['project_id'], unique=False)

    op.create_table('experimental_measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('validation_run_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('condition_json', sa.JSON(), nullable=True),
    sa.Column('replicate_id', sa.String(length=20), nullable=True),
    sa.Column('raw_data_path', sa.String(length=500), nullable=True),
    sa.Column('quality_flag', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['stamp_candidates.id'], ),
    sa.ForeignKeyConstraint(['validation_run_id'], ['experimental_validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experimental_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experimental_measurements_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experimental_measurements_validation_run_id'), ['validation_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experimental_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experimental_measurements_validation_run_id'))
        batch_op.drop_index(batch_op.f('ix_experimental_measurements_candidate_id'))

    op.drop_table('experimental_measurements')
    with op.batch_alter_table('experimental_validation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experimental_validation_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_experimental_validation_runs_candidate_id'))

    op.drop_table('experimental_validation_runs')
    with op.batch_alter_table('stamp_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stamp_candidates_project_id'))
        batch_op.drop_index(batch_op.f('ix_stamp_candidates_generation_run_id'))
        batch_op.drop_index(batch_op.f('ix_stamp_candidates_epitope_id'))

    op.drop_table('stamp_candidates')
    with op.batch_alter_table('stamp_generation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stamp_generation_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_stamp_generation_runs_epitope_id'))

    op.drop_table('stamp_generation_runs')
    with op.batch_alter_table('epitope_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epitope_candidates_scan_id'))

    op.drop_table('epitope_candidates')
    with op.batch_alter_table('epitope_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epitope_scans_target_protein_id'))
        batch_op.drop_index(batch_op.f('ix_epitope_scans_project_id'))

    op.drop_table('epitope_scans')
    with op.batch_alter_table('target_proteins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_proteins_sequence_hash'))
        batch_op.drop_index(batch_op.f('ix_target_proteins_project_id'))

    op.drop_table('target_proteins')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_batch_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('compute_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compute_batches_project_id'))

    op.drop_table('compute_batches')
    op.drop_table('projects')
    op.drop_table('integration_configs')
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_assets_job_id'))
        batch_op.drop_index(batch_op.f('ix_file_assets_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_file_assets_batch_id'))

    op.drop_table('file_assets')
    with op.batch_alter_table('computation_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_computation_artifacts_item_id'))
        batch_op.drop_index(batch_op.f('ix_computation_artifacts_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_computation_artifacts_batch_id'))

    op.drop_table('computation_artifacts')
    with op.batch_alter_table('batch_computations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_computations_project_id'))

    op.drop_table('batch_computations')
    with op.batch_alter_table('batch_computation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_computation_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_batch_computation_items_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_batch_computation_items_batch_id'))

    op.drop_table('batch_computation_items')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
